<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraduatesClub.Application\GraduatesClub.Application.csproj" />
    <ProjectReference Include="..\GraduatesClub.Infrastructure\GraduatesClub.Infrastructure.csproj" />
  </ItemGroup>
</Project>
